"""create memory tables

Revision ID: e3264bab8d11
Revises: 7a8b9c0d1e2f
Create Date: 2026-07-05 12:24:47.369247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3264bab8d11'
down_revision: Union[str, None] = '7a8b9c0d1e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('strong_topics', sa.Text(), nullable=False),
    sa.Column('weak_topics', sa.Text(), nullable=False),
    sa.Column('completed_study_plans', sa.Integer(), nullable=False),
    sa.Column('completed_interviews', sa.Integer(), nullable=False),
    sa.Column('resume_score', sa.Float(), nullable=False),
    sa.Column('placement_readiness', sa.Float(), nullable=False),
    sa.Column('last_learning_activity', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_profiles_id'), 'learning_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_learning_profiles_user_id'), 'learning_profiles', ['user_id'], unique=True)
    op.create_table('user_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('preferred_language', sa.String(length=50), nullable=False),
    sa.Column('preferred_role', sa.String(length=100), nullable=False),
    sa.Column('target_company', sa.String(length=100), nullable=False),
    sa.Column('daily_study_hours', sa.Float(), nullable=False),
    sa.Column('current_skill_level', sa.String(length=50), nullable=False),
    sa.Column('learning_style', sa.String(length=100), nullable=False),
    sa.Column('preferred_interview_type', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_learning_profiles_user_id'), table_name='learning_profiles')
    op.drop_index(op.f('ix_learning_profiles_id'), table_name='learning_profiles')
    op.drop_table('learning_profiles')
    # ### end Alembic commands ###
